# Generated by Django 5.2.1 on 2025-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_email_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant')], max_length=10),
        ),
    ]
