# Generated by Django 5.2.1 on 2025-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('meta', 'Meta'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=50),
        ),
    ]
